### ISSUE TITLE
Seems to break with HA Core 2024.8.1

### ISSUE THREAD

**Issue by trevornorcross** [Daanoz/ha-google-photos#58] opened 2024-08-12 12:17 UTC
Just wanted to identify that the Google Photos integration seems to break with 2024.8.1 (but not 2024.8.0), in the event others see the same (or to see if Daanoz/others are aware and working on this already), as I couldn't find anything about this posted yet when searching.

Here is what I saw:
1. Existing/working integrations (devices) stopped working. Was unable to read the photos/albums any further.
2. Confirmed the back end client OAuth/etc were correct, API enabled, etc. Re-configured this just in case but no change.
3. When attempting to add or re-add the album / "device" in HA, it sent me through a never ending loop of trying to re-authorize. Even though that was already done/working and didn't need refreshed.
4. Completely removing and re-adding the HACS integration didn't fix anything, nor did completely redoing the back end Google OAuth/API configuration steps.

Side note - other Google-based services which also use back end Google OAuth continued to work - also using Google Nest and Google SDK integrations which did not seem to break. So this may be specific to either Google Photos API or Google Photos integration.

I restored HA Core to 2024.8.0 and everything has been working smoothly since, while I await further guidance / acknowledgement.

Thank you.

**Comment by slickers74** [comment] 2024-08-12 13:29
Also seeing this too.

**Comment by Daanoz** [comment] 2024-08-12 17:41
Did a quick test, but could not yet confirm the issue. Any logs available when it occurs?

**Comment by slickers74** [comment] 2024-08-12 20:24
Just home to check and it seems to be working again on my home network and also on my 4G phone signal.
Was not working on my office wifi, or office PC.
I'll check again in the morning.

**Comment by Daanoz** [comment] 2024-08-16 08:02
Alright, upgraded all my test setups and home setup to 2024.8.1, but no luck reproducing it yet.

I'm starting to think it might be a combination of integrations or maybe a system limitation the integration runs into.

Could you share some details about your setup? Maybe other (google) integrations that are installed, type of system (RasberryPi, minipc, ..), number of albums in your google photos account, and amount of photos in the active albums?

**Comment by trevornorcross** [comment] 2024-08-16 12:35
**Hardware:** Home Assistant Green
**Core:** 2024.8.0 (restored from 2024.8.1 - upgrading to 2024.8.1 is immediately when my issues began)
**Supervisor:** 2024.08.0
**OS:** 13.0 (upgraded from 12.x after restoring core back to 2024.8.0 - would have been the latest 12.x during the issue I saw)
**Frontend:** 20240806.1

**Other Google integrations** - these all continued to work after going to 2024.8.1:
- Google Assistant SDK
- Google Calendar
- Google Cast
- Google Nest

I am sharing one album as a 'device' through Google Photos integration - but my account has 11 albums. The one I am sharing has 102 pictures in it (I understand you may only grab a subset at a time). 

Let me know if there's more I can provide.

**Comment by trevornorcross** [comment] 2024-08-17 11:34
To follow up, I did a full backup and implemented core 2024.8.2 (so I am skipping 2024.8.1) and that upgrade went fine, Google Photos and other integrations continue to work. Maybe a fluke at my end if others except 1 have not reported anything.

Keep in mind I did restore back to 2024.8.0 core (which was working for me) before upgrading to 2024.8.2 (working), so I don't know if someone else seeing broken functionality with 2024.8.1 would see a "fix" if they from 2024.8.1 with broken integration to 2024.8.2.

**Comment by Daanoz** [comment] 2024-08-31 08:32
Alright, did another set of testing, still can't locate the issue. The message `Setup of camera platform google_photos is taking over 10 seconds.` has been there for a while, and thats the only hint that might point to something thats off. It shouldn't break anything, as it's just a warning it's starting slow. Anyway, if I cache the available albums locally that should speed up the start up time, but that requires some refactoring of the component which I will do in due time.

For now I propose to close this issue, if anyone has new information feel free to reopen it.

**Closed by Daanoz** 2024-08-31 08:32 UTC
Labels: bug
